car/urls.py
# from django.contrib import admin
# from django.urls import path, include
# from django.conf.urls.static import static
# from django.conf import settings
#
# urlpatterns = [
#                   path('admin/', admin.site.urls),
#                   path('account/', include('django.contrib.auth.urls')),
#                   path('', include('rentcar.urls')),
#                   path('registration/', include('registration.urls')),
#                   path('signup/', include('registration.urls')),
#                   path('categories/', include('rentcar.urls')),
#                   path('buy/', include('rentcar.urls')),
#                   path('discount/', include('rentcar.urls')),
#
#               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('rentcar.urls')),
                  path('registration/', include('registration.urls')),
                  path('signup/', include('registration.urls')),
                  path('categories/', include('rentcar.urls')),
                  path('buy/', include('rentcar.urls')),
                  # path('discount/', include('rentcar.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

login/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from login.views import custom_login, profile, profile_edit, profile_delete, RegisterView

app_name = "login"

urlpatterns = [
    path("login/", custom_login, name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", profile, name="profile"),
    # path("<int:pk>/edit/", UserProfileUpdate.as_view(), name="profile_edit"),
    path("edit/", profile_edit, name="profile_edit"),
    path("delete/", profile_delete, name="profile_delete"),
    path("signup/", RegisterView.as_view(), name="signup")
]


# from django.contrib.auth.views import LogoutView
# from django.urls import path
# from login.views import AccountLoginView, AccountRegisterView
#
# app_name = 'login'
#
# urlpatterns = [#     path('login/', AccountLoginView.as_view(), name='login'),
#     path('logout/', LogoutView.as_view(), name='logout'),
#     path('signup/', AccountRegisterView.as_view(), name='signup'),
#
# ]

registration/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from registration.views import custom_login, profile, profile_edit, profile_delete, RegisterView

app_name = "registration"

urlpatterns = [
    path("registration/", custom_login, name="registration"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", profile, name="profile"),
    # path("<int:pk>/edit/", UserProfileUpdate.as_view(), name="profile_edit"),
    path("edit/", profile_edit, name="profile_edit"),
    path("delete/", profile_delete, name="profile_delete"),
    path("signup/", RegisterView.as_view(), name="signup")
]

login/forms.py
from django import forms
from django.contrib.auth.forms import UsernameField
from django.utils.translation import gettext_lazy as _

from login.models import User


class CustomAuthenticationForm(forms.Form):
    username = UsernameField(
        widget=forms.TextInput(attrs={"autofocus": True})
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password"}),
    )


class RegistrationForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm password'}))
    error_messages = {
        "password_mismatch": _("The two password fields didn’t match."),
        "username_unique": _("Username already taken."),
    }

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

    # def clean(self):
    #     data = self.cleaned_data
    #     username = self.cleaned_data.get("username")
    #     if username and self._meta.model.objects.filter(username=username).exists():
    #         raise forms.ValidationError(self.error_messages.get("username_unique"))
    #     password1 = self.cleaned_data.get("password1")
    #     password2 = self.cleaned_data.get("password2")
    #     if password1 != password2:
    #         raise forms.ValidationError(self.error_messages.get("password_mismatch"))
    #     return data

    def clean_username(self):
        username = self.cleaned_data.get("username")
        if username and self._meta.model.objects.filter(username__iexact=username).exists():
            raise forms.ValidationError(self.error_messages.get("username_unique"))
        return username

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 != password2:
            raise forms.ValidationError(self.error_messages.get("password_mismatch"))
        return password2


class UserUpdateForm(forms.ModelForm):
    birth_date = forms.DateField(required=False)

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email", "phone_number", "birth_date", "profile_picture")

login/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.messages import get_messages
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView

from login.forms import RegistrationForm, CustomAuthenticationForm, UserUpdateForm
from login.models import User


class AccountLoginView(LoginView):
    form_class = CustomAuthenticationForm
    template_name = "login/login.html"


def custom_login(request):
    form = CustomAuthenticationForm(request.POST or None)
    if form.is_valid():
        username = request.POST.get("username")
        password = request.POST.get("password")
        if username is not None and password:
            user = authenticate(
                request, username=username, password=password
            )
            login(request, user)
            return redirect("login:login")
    return render(request, "login/login.html", {"form": form})


class RegisterView(CreateView):
    model = User
    template_name = 'login/signup.html'
    form_class = RegistrationForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST or None)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            first_name = form.cleaned_data.get("first_name")
            last_name = form.cleaned_data.get("last_name")
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password1")
            user = User.objects.create_user(username, email, password, first_name=first_name, last_name=last_name)
            login(request, user)
            return redirect("homepage")
        return render(request, "login/signup.html", {"form": form, 'messages': get_messages(request)})


class UserProfile(DetailView, LoginRequiredMixin):
    model = User
    pk_url_kwarg = None
    query_pk_and_slug = None

    def get_queryset(self):
        return self.request.user


@login_required
def profile(request):
    return render(request, "login/profile.html", {"user": request.user})


class UserProfileUpdate(UpdateView, LoginRequiredMixin):
    model = User
    form_class = UserUpdateForm
    template_name = "login/profile_edit.html"
    success_url = reverse_lazy("login:profile")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = self.request.user
        return context

    def put(self, *args, **kwargs):
        form = self.form_class(self.request.POST or None, self.request.FILES or None)
        if form.is_valid():
            form.save()
        return render(self.request, "login/profile_edit.html", {"form": form})


@login_required()
def profile_edit(request):
    if request.POST:
        form = UserUpdateForm(request.POST or None, request.FILES or None, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("login:profile")
    else:
        form = UserUpdateForm()
    return render(request, "login/profile_edit.html", {"form": form})


@login_required()
def profile_delete(request):
    user = request.user
    user.delete()
    return redirect("homepage")

templates/login/login.html
{#{% extends 'base.html' %}#}
{#{% load static %}#}
{#{% block content %}#}
{#    <link href="{% static 'registration.css' %}" rel="stylesheet">#}
{#    <body>#}
{##}
{#    <div id="card">#}
{#        <div id="card-content">#}
{#            <div id="card-title" class="left">#}
{#                <h2>LOGIN</h2>#}
{#                <div class="underline-title"></div>#}
{#            </div>#}
{#            <form method="post" class="form">#}
{#                <label for="user-email" style="padding-top:13px">#}
{#                    &nbsp;Email#}
{#                </label>#}
{#                <input id="user-email" class="form-content" type="email" name="email" autocomplete="on" required/>#}
{#                <div class="form-border"></div>#}
{#                <label for="user-password" style="padding-top:22px">&nbsp;Password#}
{#                </label>#}
{#                <input id="user-password" class="form-content" type="password" name="password" required/>#}
{#                <div class="form-border"></div>#}
{#                <a href="#">#}
{#                    <legend id="forgot-pass">Forgot password?</legend>#}
{#                </a>#}
{#                <input id="submit-btn" type="submit" name="submit" value="LOGIN"/>#}
{#                <a href="#" id="signup">Don't have account yet?</a>#}
{#            </form>#}
{#        </div>#}
{#    </div>#}
{#{% endblock %}#}
{% extends 'base.html' %}

{% block content %}
    <h1>Login</h1>
    <form action="{% url 'registration:registration' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {#        <label for="username">Username:</label>#}
        {#        <input type="text" id="username" name="username">#}
        {#        <label for="password">Password:</label>#}
        {#        <input type="password" id="password" name="password">#}
        <input type="submit" value="Login">
    </form>

{% endblock %}

templates/login/profile.html
{% extends 'base.html' %}

{% block title %}
    {{ user.first_name }} {{ user.last_name }} - Profile
{% endblock %}

{% block style %}
    <style>
        .gradient-custom {
            /* fallback for old browsers */
            background: white;

            /* Chrome 10-25, Safari 5.1-6 */
            background: -webkit-linear-gradient(to right bottom, rgb(51, 98, 200), rgb(110, 88, 158));

            /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
            background: linear-gradient(to right bottom, rgb(51, 98, 200), rgb(110, 88, 158))
        }

        .navbar {
            margin-bottom: 0;
        }
    </style>
{% endblock %}

{% block content %}
    <section class="vh-100" style="background-color: #f4f5f7;">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col col-lg-6 mb-4 mb-lg-0">
                    <div class="card mb-3" style="border-radius: .5rem;">
                        <div class="row g-0">
                            <div class="col-md-4 gradient-custom text-center text-white"
                                 style="border-top-left-radius: .5rem; border-bottom-left-radius: .5rem;">
                                {% if user.profile_picture %}
                                    <img src="{{ user.profile_picture.url }}"
                                         alt="Avatar" class="img-fluid my-5" style="width: 80px;"/>
                                {% else %}
                                    <img src="https://www.freeiconspng.com/thumbs/profile-icon-png/am-a-19-year-old-multimedia-artist-student-from-manila--21.png"
                                         alt="Avatar" class="img-fluid my-5" style="width: 80px;"/>
                                {% endif %}
                                <h5>{{ user.username }}</h5>
                                <p>Username</p>
                                <i class="far fa-edit mb-5"></i>
                            </div>
                            <div class="col-md-8">
                                <div class="card-body p-4">
                                    <h6>{{ user.first_name }} {{ user.last_name }}</h6>
                                    <hr class="mt-0 mb-4">
                                    <div class="row pt-1">
                                        <div class="col-6 mb-3">
                                            <h6>Email</h6>
                                            <p class="text-muted">{{ user.email }}</p>
                                        </div>
                                        <div class="col-6 mb-3">
                                            <h6>Last login</h6>
                                            <p class="text-muted">{{ user.last_login|date }}</p>
                                        </div>
                                        <a href="{% url 'registration:profile_edit' %}">Edit profile</a>
                                        <a href="{% url 'registration:profile_delete' %}">Delete profile</a>
                                    </div>
                                    <div class="d-flex justify-content-start">
                                        <a href="#!"><i class="fab fa-facebook-f fa-lg me-3"></i></a>
                                        <a href="#!"><i class="fab fa-twitter fa-lg me-3"></i></a>
                                        <a href="#!"><i class="fab fa-instagram fa-lg"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/login/profile_edit.html
{% extends 'base.html' %}

{% block content %}

    <form action="{% url 'registration:profile_edit' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>

{% endblock %}

templates/login/profile_editl.html
{% extends 'base.html' %}

{% block content %}

    <form action="{% url 'login:profile_edit' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>

{% endblock %}

templates/login/signup.html
{#{% extends 'base.html' %}#}
{#{% load static %}#}
{#{% block content %}#}
{#    <link href="{% static 'registration.css' %}" rel="stylesheet">#}
{#    <body>#}
{##}
{#    <div id="card">#}
{#        <div id="card-content">#}
{#            <div id="card-title" class="left">#}
{#                <h2>Sign up</h2>#}
{#                <div class="underline-title"></div>#}
{#            </div>#}
{#            <form method="post" class="form">#}
{#                <label for="user-firstname" style="padding-top:13px">#}
{#                    &nbsp;Username#}
{#                </label>#}
{#                <input id="user-firstname" class="form-content" type="firstname" name="firstname" autocomplete="on"#}
{#                       required/>#}
{#                <div class="form-border"></div>#}
{#                <label for="user-phonenumber" style="padding-top:13px">#}
{#                    &nbsp;Phone number#}
{#                </label>#}
{#                <input id="user-phonenumber" class="form-content" type="phonenumber" name="phonenumber" autocomplete="on" required/>#}
{#                <div class="form-border"></div>#}
{#                <label for="user-email" style="padding-top:13px">#}
{#                    &nbsp;Email#}
{#                </label>#}
{#                <input id="user-email" class="form-content" type="email" name="email" autocomplete="on" required/>#}
{#                <div class="form-border"></div>#}
{#                <label for="user-password" style="padding-top:22px">&nbsp;Password#}
{#                </label>#}
{#                <input id="user-password" class="form-content" type="password" name="password" required/>#}
{#                <div class="form-border"></div>#}
{#                <a href="#">#}
{#                    <legend id="forgot-pass">Forgot password?</legend>#}
{#                </a>#}
{#                <input id="submit-btn" type="submit" name="submit" value="Sign Up"/>#}
{#                <a href="#" id="signup">Don't have account yet?</a>#}
{#            </form>#}
{#        </div>#}
{#    </div>#}
{#{% endblock %}#}
{% extends 'base.html' %}

{% block content %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
            {% endfor %}
        </ul>
    {% endif %}
    <h1>Register</h1>
    <form action="{% url 'registration:signup' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endblock %}