car/urls.py
# from django.contrib import admin
# from django.urls import path, include
# from django.conf.urls.static import static
# from django.conf import settings
#
# urlpatterns = [
#                   path('admin/', admin.site.urls),
#                   path('account/', include('django.contrib.auth.urls')),
#                   path('', include('rentcar.urls')),
#                   path('registration/', include('registration.urls')),
#                   path('signup/', include('registration.urls')),
#                   path('categories/', include('rentcar.urls')),
#                   path('buy/', include('rentcar.urls')),
#                   path('discount/', include('rentcar.urls')),
#
#               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('rentcar.urls')),
                  path('registration/', include('registration.urls')),
                  path('signup/', include('registration.urls')),
                  path('categories/', include('rentcar.urls')),
                  path('buy/', include('rentcar.urls')),
                  # path('discount/', include('rentcar.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

registration/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from registration.views import custom_login, profile, profile_edit, profile_delete, RegisterView

app_name = "registration"

urlpatterns = [
    path("registration/", custom_login, name="registration"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", profile, name="profile"),
    # path("<int:pk>/edit/", UserProfileUpdate.as_view(), name="profile_edit"),
    path("edit/", profile_edit, name="profile_edit"),
    path("delete/", profile_delete, name="profile_delete"),
    path("signup/", RegisterView.as_view(), name="signup")
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book store</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link href="{% static 'style.css' %}" rel="stylesheet">
    <style>
        .nav-item {
            margin-left: 5px;
        }
    </style>
    {% block style %}{% endblock %}
</head>
<body>

<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">">

    <div class="container-fluid">
        <a class="navbar-brand" href="#"><span style="color: #ffffff">i8 Rent Car Service</span></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="http://127.0.0.1:8000/discount/">Discounts
                        📉</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "categories" %}">Car categories</a>
                </li>
                <li>
                    <a class="nav-link" href="#"><span style="color: #eecd3c">Honesty > trumps profit</span></a>
                </li>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'registration:profile' %}">
                        <button type="button" class="btn btn-success">Profile</button>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'registration:logout' %}">
                        <button type="button" class="btn btn-primary">Logout</button>
                    </a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'registration:registration' %}">
                        <button type="button" class="btn btn-success">Login</button>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'registration:signup' %}">
                        <button type="button" class="btn btn-primary">Register</button>
                    </a>
                </li>
            {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block style %}
    <style>
        .home {
            float: right;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="cards-container">
        <a id="toptop"></a>
        {% for car in cars %}
            <div class="card">
                <img src="{{ car.image.url }}" class="card-img-top" alt="{{ car.image.url }}">
                <div class="card-body">
                    <h5 class="card-title"><span style="color:red">{{ car.title }}</span></h5>
                    {% if car.description|length > 80 %}
                        <p class="card-text">{{ car.description|slice:100}}</p>
                    {% else %}
                        <p class="card-text">{{ car.description }}</p>
                    {% endif %}

                    <a href="{% url 'more' car.id %}" class="btn btn-primary">See more 👀</a>
                </div>
            </div>
        {% endfor %}
        <a class="btn btn-primary home" href="#toptop">⬆ Homepage </a>

    </div>
{% endblock %}